### ISSUE TITLE
Make it possible to have grey background for 2-color cards

### ISSUE THREAD

**Issue by robinmoussu** [shardofhonor/dominion-card-generator#13]
Cards like [village green](http://wiki.dominionstrategy.com/index.php/Village_Green) have 3 types, and the color of the description is *Action* (grey), while the border is *Reaction/Duration* (blue/orange). It’s currently not possible to reproduce it.

I’m not sure if a third category of color is needed (more flexible, but weights down the interface), or if a new type of split (always grey) would be enough.

**Comment by robinmoussu** [comment]
The kind of blend I would like is exactly what is done when the secondary color is "SAME".

**Comment by shardofhonor** [comment]
I've just committed support for a new Split-Color option that could be used to recreate [Village Green](https://shardofhonor.github.io/dominion-card-generator/?title=Village%20Green&description=Either%20now%20or%20at%20the%20%0Astart%20of%20your%20next%20turn%2C%20%0A%2B1%20Card%20and%20%2B2%20Actions.%0A%0A-%0A%0AWhen%20you%20discard%20this%20other%20than%20during%20Clean-up%2C%20you%20may%20reveal%20it%20to%20play%20it.&type=Action%20-%20Duration%20-%20Reaction&credit=&creator=&price=%244&preview=&type2=&color2split=27&boldkeys=&picture-x=0&picture-y=0&picture-zoom=1&picture=http%3A%2F%2Fwiki.dominionstrategy.com%2Fimages%2F0%2F01%2FVillage_GreenArt.jpg&expansion=http%3A%2F%2Fwiki.dominionstrategy.com%2Fimages%2Fd%2Fd4%2FMenagerie_%2528expansion%2529_icon.png&custom-icon=&color0=3&color1=5&size=0)
