### ISSUE TITLE
Custom Icon Cross-Origin Error

### ISSUE THREAD

**Issue by alddesign** [shardofhonor/dominion-card-generator#14]
First of all: good work!

Getting an error when providing an external url for icons like: http://example.com/icon.png

I think you are aware of that because JS console says "CORS loading of external resources deactivated".
It would be a nice feature though. 

A workaround for this problem could be:
Instead of loading the image directrly into the canvas (via JS), you could use some server side scripting to get rid of the Cross Origin problem:
-Send the imgage url "http://example.com/icon.png" to a serverside script (i use PHP for example)
-Let PHP download the image
-Return a base64 string of the image
-Use this response for your img.src

I know github.io doesnt support php, but i maybe youll find a way. 
I used this code for a very similar project (yugioh card creator):

[getImageBase64.zip](https://github.com/shardofhonor/dominion-card-generator/files/6872282/getImageBase64.zip)

**Comment by shardofhonor** [comment]
Thanks! I'm currently using an own [CORS-anywhere](https://github.com/Rob--W/cors-anywhere) instance dedicated to this, but the free Heroku tier is sometimes depleted at the end of the month...

**Comment by shardofhonor** [comment]
Closed, as the current architecture with _free_ hosting as GitHub page shall be kept and the CORS-anywhere solution works most of the month.
