### ISSUE TITLE
This is not in the Supply

### ISSUE THREAD

**Issue by PetziPotato** [shardofhonor/dominion-card-generator#16]
It's not possible to add _(This is not in the Supply.)_ like in the official cards, because the line gets cut off. This also causes the word "Supply" to not be in italic, which is probably a bug?

One thing to note is that it stays in a single line if you don't add the italic mark. The italic doesn't seem to add much width to the text, so it looks like maybe the [i] is taken into account as 3 extra characters when deciding to add a line break.

It works fine it you write "supply" instead of "Supply" and there's even a special string for that in the code, it just bugs me that it doesn't exactly match the official cards 😅

Text in each image:
`[i](This is not in the Supply.)`
`(This is not in the Supply.)`

<img src="https://user-images.githubusercontent.com/11427568/141132046-ab5f6899-9a9a-4260-bf20-1c5bb7ac0dfa.png" width="300"/> <img src="https://user-images.githubusercontent.com/11427568/141132398-4ca6f5a8-70e4-4cf7-9835-36ea2a0ba147.png" width="300"/>

**Comment by shardofhonor** [comment]
Thanks! I've fixed the issue. (might require clearing of the cache, at least for the .js-file)
Example: [Horse](https://shardofhonor.github.io/dominion-card-generator/?title=Horse&description=%2B2%20Cards%0A%2B1%20Action%0A%0AReturn%20this%20to%20its%20pile.%0A%0A%0A(This%20is%20not%20in%20the%20Supply.)&type=Action&credit=Illustration%3A%20Claus%20Stephan&creator=%C2%A9%202020%20Rio%20Grande%20Games%20&price=%243*&preview=&type2=&color2split=1&boldkeys=&picture-x=0&picture-y=0&picture-zoom=1&picture=http%3A%2F%2Fwiki.dominionstrategy.com%2Fimages%2F4%2F41%2FHorseArt.jpg&expansion=http%3A%2F%2Fwiki.dominionstrategy.com%2Fimages%2Fd%2Fd4%2FMenagerie_%2528expansion%2529_icon.png&custom-icon=&color0=0&color1=0&size=0) is now working.
